create table webauthtokens (
                       id integer generated by default as identity primary key,
                       token text not null unique,
                       FOREIGN KEY (id) REFERENCES users(id)
);